---
apiVersion: v1
kind: Service
metadata:
  name: nvidia-gpu-mem-monitor
  namespace: devops
  labels:
    app: nvidia-gpu-mem-monitor
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "59500"
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: nvidia-gpu-mem-monitor
    targetPort: 59500
  selector:
    app: nvidia-gpu-mem-monitor
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-gpu-mem-monitor
  namespace: devops
spec:
   selector:
     matchLabels:
       app: nvidia-gpu-mem-monitor
   template:
     metadata:
       labels:
         app: nvidia-gpu-mem-monitor
       annotations:
         sidecar.istio.io/inject: 'false'
     spec:
       affinity:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
               - key: gpu
                 operator: Exists
             - matchExpressions:
               - key: gpushare
                 operator: Exists
             - matchExpressions:
               - key: daipops
                 operator: In
                 values:
                 - gpushare
       tolerations:
       - operator: Exists
         effect: NoSchedule
       containers:
       - name: nvidia-gpu-mem-monitor
         image: IMAGE_TAG_NAME
         ports:
         - containerPort: 59500
         env:
         - name: TZ
           value: Asia/Shanghai
         - name: hostIP
           valueFrom:
             fieldRef:
               apiVersion: v1
               fieldPath: status.hostIP
         volumeMounts:
         - name: proc
           mountPath: /proc
         - name: socket
           mountPath: /var/run/docker.sock
       volumes:
       - name: proc
         hostPath:
           path: /proc
       - name: socket
         hostPath:
           path: /var/run/docker.sock